### ISSUE TITLE
Need to run cmake twice to set the install prefix properly

### ISSUE THREAD

**Issue by guiguem** [project8/scarab#24]
When a specific installation location is desired, using `cmake -D CMAKE_INSTALL_PREFIX=/my/location/folder ..` does not do that
This is a bug, for which the current solution is to run this command twice...

Low priority, but annoying bug when we don't know the answer.

**Comment by laroque** [comment]
I think we've seen this elsewhere also. I don't remember solving it, or which package that was. We should be sure to note what the solution is if we find it (also crosslink the issues if we come across them).

**Comment by nsoblath** [comment]
This is a known feature with the PackageBuilder cmake setup.  I would agree that it's undesirable, but I'm going to change the label because I don't think it qualifies as a bug.

Here's the relevant code from PackageBuilder.cmake:

```

**Comment by nsoblath** [comment]
I remember a bit more about why this feature exists.  When I was initially putting PackageBuilder together I wanted the default install prefix to be the build directory.  I found that if I set the install prefix in the PackageBuilder.cmake file, it always overruled the user's CL specification.  It would be nice if there was a way to set the default prefix and then have any specifications by the user override that, but at the time I didn't find that.  So instead I set it up so that it only sets the default prefix if the `SET_INSTALL_PREFIX_TO_DEFAULT` flag is true or if it doesn't exist yet.  That variable, unlike `CMAKE_INSTALL_PREFIX`, does not exist at this point in the CMake process the first time CMake is run, so it works as a thing to check whether the install prefix should be set.
