### ISSUE TITLE
Documentation: list of the dependencies

### ISSUE THREAD

**Issue by guiguem** [project8/scarab#25]
It seems that Scarab needs boost.
This issue should track the other dependencies it needs...

**Comment by nsoblath** [comment]
The dependencies for the C++ library are listed in library/README.md.  It's done this way because of how scarab is conceptually organized: there are three semi-independent modules, cmake, githooks (not currently used), and the library.  So I put the library-specific information in the library readme.  If a different organization is desired, let's discuss that in a different issue.
