### ISSUE TITLE
Modifier Syntax

### ISSUE THREAD

**Issue by nsoblath** [project8/scarab#63]
@buzinsky is working on the implementation of the modifier framework and initial modifiers here: https://github.com/project8/scarab/pull/62.

And the description of the initial syntax choice: https://github.com/project8/scarab/pull/62#issue-377367569

We need to come to a consensus on the syntax we'll use.

**Comment by nsoblath** [comment]
I have two main comments regarding the initial choice of syntax:

1. The environment variable syntax should not restrict the choice of variable names as it currently does.  As it stands the variable name must start with `DRIPLINE_`.  First of all, Scarab is not specific to Dripline, so that choice of prefix doesn't make sense.  Second, I think that the config file should be responsible for specifying which substitutions are coming from environment variables, instead of relying on the choice of variable name.

2. I think it would be better to try to stay away from common variable indicators like `$` and go with something unique that won't conflict with scripting languages, or template engines, etc.

**Comment by nsoblath** [comment]
So far the set of operations I've thought of for potential implementation as modifiers is:

1. Environment variable substitution
2. Local variable declaration/definition
3. Local variable substitution
4. Expression evaluation
5. File inclusion
6. Internal links

As I guide I was assuming that we'd want to have unique syntax, so the syntax doesn't conflict with other common syntaxes.  I sketched out an initial idea for items 1-3 above a while back.  I'm not particularly tied to the exact symbols used.

Define a variable
```
    >>var_name: any_param
```

Use a variable
```
    a_value: <<var_name
```

Use a variable inline
```
    a_value: "hello, <<{var_name}, how are you?"
```

Use an environment variable
```
    a_value: <<ENV{VAR_NAME}
```

Use an environment variable inline
```
    a_value: "hello, <<ENV{VAR_NAME}, how are you?"
```

**Comment by laroque** [comment]
Hm.. So the YAML syntax actually already supports 2/3 I think with "anchors" and "aliases" (first hit: https://confluence.atlassian.com/bitbucket/yaml-anchors-960154027.html).

Is our processing coming before or after the yaml parser converts the string to a param? If before then we could land in a state that the parser will resolve with alias expansions If it comes after, then our syntax needs to be valid yaml for the parser (and we need to be careful about the fact that the yaml parser will do all valid parsing including anchor/alias stuff, which may or may not be what we want/expect)

**Comment by nsoblath** [comment]
This processing is all after the YAML file is parsed and other inputs to the configuration have been handled (CL arguments).  The exception to that could be the file-inclusion idea, but I want to leave that aside completely, since file inclusion is further in the future.

Having these features in scarab gives us more flexibility than the features as implemented in YAML because the configuration process is larger than just YAML parsing.  Not only does it include other inputs like the CL arguments, but it can come from other file types (with JSON being the only other one currently implemented).

Having unique syntax from the YAML syntax and taking place after things are converted to the param structure avoids conflicts with YAML parsing (I think).

**Comment by buzinsky** [comment]
While I don't have issues with the proposed syntax in general, I do have initial concerns about implementing the local variable assignment/ substitution in the yaml file, if we do not use the this native YAML anchoring.

Specifically, I am not certain that the order with which lines are put into the config is retained, within the master_config structure, since from what I can tell, the param_node class (or really the contents) is basically a <map>, which is ordered, but not in the sense of a deque/ vector: I thought that the map sorts elements (eg alphabetically) by key value. I vaguely recall noticing in the debug messages that the printed config was not ordered the same as the actual config file.

I think that losing ordering would make variable definition/ substitution much tougher. Well, in any case, I think we need to either a) somehow retain this information about order, or b) have local variables be "const" ie, cannot be reassigned, though I am not sure if this is enough. 

You can imagine how few of your programs work if the commands are scrambled.

Avoiding cases where someone tries to:
```    >>A: <<B
      >>B: <<A ```
(or inadvertently does so because the lines are mixed up) should be avoided. Ideally, we should be throwing an error that B is undefined

**Comment by nsoblath** [comment]
This was completed in faec317b05917e8fdd20ddb8524ac4818fed166a
